import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:impact/providers/firebase_provider.dart';
import 'package:impact/providers/raffle_form_provider.dart';
import 'package:impact/screens/forms/models/raffle_form.dart';
import 'package:impact/screens/forms/raffle/raffle_form_advanced.dart';
import 'package:impact/screens/forms/raffle/raffle_form_customization.dart';
import 'package:impact/screens/forms/raffle/raffle_form_general.dart';

class RaffleScreen extends ConsumerStatefulWidget {
  const RaffleScreen({super.key});

  @override
  ConsumerState createState() => _RaffleScreenState();
}

class _RaffleScreenState extends ConsumerState<RaffleScreen> {
  int currentStep = 0;

  final _generalFormKey = GlobalKey<FormState>();

  publishRaffleForm() async {
    final newRaffleForm = RaffleForm(
      id: '', // Will be generated by Firestore
      ownerId: ref.read(currentUserIDProvider),
      createdTime: DateTime.now(),
      title: ref.read(raffleTitleControllerProvider).text,
      language: ref.read(raffleFormLanguageProvider),
      description: ref.read(raffleDescriptionQuillController).document.toDelta().toJson(),
      raffleDates: ref.read(raffleDatesProvider),
      themeColor: ref.read(raffleThemeColorProvider) ?? '#6200EE',
      logoUrl: ref.read(raffleLogoUrlProvider) ?? '',
      bannerUrl: ref.read(raffleBannerUrlProvider) ?? '',
      ticketOptions: ref.read(raffleTicketOptionsProvider),
      salesTarget: ref.read(raffleSalesTargetProvider),
      suggestCheckPayment: ref.read(raffleSuggestCheckPaymentProvider),
      enableDiscountCodes: ref.read(raffleEnableDiscountCodesProvider),
      notificationEmails: ref.read(raffleNotificationEmailsControllerProvider).text,
      shareableLink: '', // Will be generated by Firestore
      status: 'active', // Default status
    );
    await ref.read(firestoreServiceProvider).addRaffleForm(newRaffleForm);
    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Raffle form created!")));
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF6A4CBC)),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text("Create Raffle Form", style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold)),
        centerTitle: true,
      ),
      body: Stepper(
        steps: [
          Step(
            title: Text("General"),
            content: RaffleFormGeneral(formKey: _generalFormKey),
            isActive: currentStep == 0,
            state: currentStep > 0 ? StepState.complete : StepState.indexed,
          ),
          Step(
            title: Text("Customization"),
            content: RaffleFormCustomization(),
            isActive: currentStep == 1,
            state: currentStep > 1 ? StepState.complete : StepState.indexed,
          ),
          Step(
            title: Text("Advanced"),
            content: RaffleFormAdvanced(),
            isActive: currentStep == 2,
          ),
        ],
        type: StepperType.horizontal,
        onStepTapped: (index) {
          setState(() {
            currentStep = index;
          });
        },
        currentStep: currentStep,
        onStepContinue: () {
          if (currentStep == 0 && !_generalFormKey.currentState!.validate()) return;

          if (currentStep != 2) {
            setState(() {
              currentStep += 1;
            });
          }
        },
        onStepCancel: () {
          if (currentStep != 0) {
            setState(() {
              currentStep -= 1;
            });
          }
        },
        controlsBuilder: (context, details) {
          return Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (currentStep != 2)
                ElevatedButton(
                  onPressed: details.onStepContinue,
                  child: Text("Continue"),
                ),
              if (currentStep == 2)
                ElevatedButton(
                  onPressed: () async {
                    await publishRaffleForm();
                  },
                  child: Text("Publish"),
                ),
              if (currentStep != 0)
                ElevatedButton(
                  onPressed: details.onStepCancel,
                  child: Text("Back"),
                ),
            ],
          );
        },
      ),
    );
  }
}
