import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:impact/providers/firebase_provider.dart';
import 'package:impact/providers/peer_to_peer_form_provider.dart';
import 'package:impact/screens/forms/models/peer_to_peer_form.dart';
import 'package:impact/screens/forms/peer_to_peer/peer_form_advanced.dart';
import 'package:impact/screens/forms/peer_to_peer/peer_form_customization.dart';
import 'package:impact/screens/forms/peer_to_peer/peer_form_general.dart';

class PeerToPeerScreen extends ConsumerStatefulWidget {
  const PeerToPeerScreen({super.key});

  @override
  ConsumerState createState() => _PeerToPeerScreenState();
}

class _PeerToPeerScreenState extends ConsumerState<PeerToPeerScreen> {
  final GlobalKey<FormState> _generalFormKey = GlobalKey<FormState>(); // ✅ Form key

  publishPeerToPeerForm() async {
    final newPeerToPeerForm = PeerToPeerForm(
      id: '', // Will be generated by Firestore
      ownerId: ref.read(currentUserIDProvider),
      createdTime: DateTime.now(),
      title: ref.read(peerToPeerTitleControllerProvider).text,
      language: ref.read(peerToPeerFormLanguageProvider),
      generateTaxReceipt: ref.read(peerToPeerGenerateTaxReceiptProvider),
      goalAmount: double.tryParse(ref.read(peerToPeerGoalAmountControllerProvider).text) ?? 0.0,
      description: ref.read(peerToPeerDescriptionQuillController).document.toDelta().toJson(),
      fundraiserMessage: ref.read(peerToPeerFundraiserMessageQuillController)?.document.toDelta().toJson() ?? [],
      suggestedAmounts: ref.read(peerToPeerSuggestedAmountsProvider),
      themeColor: ref.read(peerToPeerThemeColorProvider) ?? '#6200EE',
      logoUrl: ref.read(peerToPeerLogoUrlProvider) ?? '',
      bannerUrl: ref.read(peerToPeerBannerUrlProvider) ?? '',
      donorQuestions: ref.read(peerToPeerDonorQuestionsProvider),
      emailSubject: ref.read(peerToPeerEmailSubjectControllerProvider).text,
      emailBody: ref.read(peerToPeerEmailQuillProvider).document.toPlainText(),
      addSalesTarget: ref.read(peerToPeerAddSalesTargetProvider),
      suggestCheckPayment: ref.read(peerToPeerSuggestCheckPaymentProvider),
      addDiscountCodes: ref.read(peerToPeerAddDiscountCodesProvider),
      notificationEmails: ref.read(peerToPeerNotificationEmailsControllerProvider).text,
      shareableLink: '', // Will be generated by Firestore
      status: 'active', // Default status
    );
    await ref.read(firestoreServiceProvider).addPeerToPeerForm(newPeerToPeerForm);
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(const SnackBar(content: Text("Peer-To-Peer form created!")));

    Navigator.pop(context);
  }

  int currentStep = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Color(0xFF6A4CBC)),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          "Create Peer-to-Peer Form",
          style: Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight: FontWeight.bold),
        ),
        centerTitle: true,
      ),
      body: Stepper(
        steps: [
          Step(
            title: Text("General"),
            content: PeerFormGeneral(formKey: _generalFormKey), // ✅ pass form key
            isActive: currentStep == 0,
            state: currentStep > 0 ? StepState.complete : StepState.indexed,
          ),
          Step(
            title: Text("Customization"),
            content: PeerFormCustomization(),
            isActive: currentStep == 1,
            state: currentStep > 1 ? StepState.complete : StepState.indexed,
          ),
          Step(
            title: Text("Advanced"),
            content: PeerFormAdvanced(),
            isActive: currentStep == 2,
          ),
        ],
        type: StepperType.horizontal,
        onStepTapped: (index) {
          setState(() {
            currentStep = index;
          });
        },
        currentStep: currentStep,
        onStepContinue: () {
          if (currentStep == 0) {
            if (_generalFormKey.currentState?.validate() ?? false) {
              setState(() => currentStep += 1);
            }
          } else if (currentStep < 2) {
            setState(() => currentStep += 1);
          }
        },
        onStepCancel: () {
          if (currentStep != 0) {
            setState(() {
              currentStep -= 1;
            });
          }
        },
        controlsBuilder: (context, details) {
          return Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              if (currentStep != 2)
                ElevatedButton(
                  onPressed: details.onStepContinue,
                  child: Text("Continue"),
                ),
              if (currentStep == 2)
                ElevatedButton(
                  onPressed: () async {
                    //await publishDonationForm();
                  },
                  child: Text("Publish"),
                ),
              if (currentStep != 0)
                ElevatedButton(
                  onPressed: details.onStepCancel,
                  child: Text("Back"),
                ),
            ],
          );
        },
      ),
    );
  }
}
